name: sample
description: Just a sample application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.0.0
  dio: ^3.0.10
  functional_data: ^0.3.0
  equatable: ^1.2.3
  get_it: ^4.0.4
  cached_network_image: ^2.3.2+1
  json_annotation: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.2
  functional_data_generator: 0.3.4
  build_verify: 1.1.1
  json_serializable: 3.4.1

flutter:

  uses-material-design: true
